apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}