{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}

spec:
  replicas: {{ .replicaCount }}

  selector:
    matchLabels:
      app: {{ .name }}

  template:
    metadata:
      labels:
        app: {{ .name }}

    spec:
      containers:
        - name: {{ .name }}

          image: "{{ .image.repository }}:{{ .image.tag }}"

          imagePullPolicy: {{ .image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: hospital-config
            - secretRef:
                name: hospital-secrets
          ports:
            - containerPort: {{ .containerPort }}

{{- end }}